#include "water.h"

Water::Water(Shader* shader, WaterFrameBuffers* fbos)
    : Node(glm::mat4(1.0f)), shader_(shader->get_id()), fbos_(fbos)
{
    // square
    float size = 10000.0f;
    float vertices[] = {
        -size, 0.0f, -size,
        -size, 0.0f,  size,
         size, 0.0f, -size,
         size, 0.0f, -size,
        -size, 0.0f,  size,
         size, 0.0f,  size
    };

    glGenVertexArrays(1, &VAO);
    glGenBuffers(1, &VBO);
    glBindVertexArray(VAO);
    glBindBuffer(GL_ARRAY_BUFFER, VBO);
    glBufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STATIC_DRAW);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 3 * sizeof(float), (void*)0);
    glBindVertexArray(0);

    glUseProgram(shader_);
    glUniform1i(glGetUniformLocation(shader_, "reflectionTexture"), 0);
    glUniform1i(glGetUniformLocation(shader_, "refractionTexture"), 1);
    glUseProgram(0);
}

Water::~Water() {
    glDeleteVertexArrays(1, &VAO);
    glDeleteBuffers(1, &VBO);
}

void Water::draw(glm::mat4& model, glm::mat4& view, glm::mat4& projection) {
    glUseProgram(shader_);
    glUniform3f(
        glGetUniformLocation(shader_, "fogColor"),
        0.7f, 0.8f, 0.9f
    );

    glUniform1f(
        glGetUniformLocation(shader_, "fogDensity"),
        1.5f   
    );

    // Bind textures generated by FBOs
    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, fbos_->getReflectionTexture());
    glActiveTexture(GL_TEXTURE1);
    glBindTexture(GL_TEXTURE_2D, fbos_->getRefractionTexture());

    glUniformMatrix4fv(glGetUniformLocation(shader_, "model"), 1, GL_FALSE, &model[0][0]);
    glUniformMatrix4fv(glGetUniformLocation(shader_, "view"), 1, GL_FALSE, &view[0][0]);
    glUniformMatrix4fv(glGetUniformLocation(shader_, "projection"), 1, GL_FALSE, &projection[0][0]);

    glBindVertexArray(VAO);
    glDrawArrays(GL_TRIANGLES, 0, 6);
    glBindVertexArray(0);
}